import { supabase } from '../lib/supabaseClient.js';

/**
 * Creates a unique SHA-256 hash using the Web Crypto API
 * @param {string} message 
 * @returns {Promise<string>}
 */
const generateHash = async (message) => {
  const msgBuffer = new TextEncoder().encode(message);
  const hashBuffer = await crypto.subtle.digest('SHA-256', msgBuffer);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
};

/**
 * Generates an immutable audit report for a specific application.
 * @param {string} applicationId - UUID of the loan application
 * @param {string} generatedBy - Name of the user/system creating the report
 * @returns {Promise<{json: any, md: string, hash: string}>}
 */
export const generateAuditReport = async (applicationId, generatedBy = 'SYSTEM') => {
  try {
    // 1. Fetch Session Data
    const { data: loanApp, error: appError } = await supabase
      .from('loan_applications')
      .select('*, profiles(name, phone)')
      .eq('id', applicationId)
      .single();
    
    if (appError) throw appError;

    // 2. Fetch KYC Data
    const { data: kycData } = await supabase
      .from('kyc_records')
      .select('*')
      .eq('application_id', applicationId)
      .single();

    // 3. Fetch Events
    const { data: events, error: eventsError } = await supabase
      .from('application_events')
      .select('*')
      .eq('application_id', applicationId)
      .order('created_at', { ascending: true });

    // 4. Fetch Consent Records
    const { data: consents } = await supabase
      .from('consent_records')
      .select('*')
      .eq('application_id', applicationId)
      .order('created_at', { ascending: true });
      
    // 5. Build JSON Payload
    const reportJson = {
      audit_meta: {
        generated_at: new Date().toISOString(),
        generated_by: generatedBy,
        system_version: "2.5.0-compliance",
        environment: {
          userAgent: navigator.userAgent,
          platform: navigator.platform
        }
      },
      application_state: {
        id: loanApp.id,
        user: loanApp.profiles?.name || 'Unknown',
        phone: loanApp.profiles?.phone || 'Unknown',
        stage: loanApp.application_stage,
        status: loanApp.status,
        created_at: loanApp.created_at,
        updated_at: loanApp.updated_at
      },
      risk_assessment: {
        fraud_score: loanApp.fraud_risk_score,
        trust_score: loanApp.trust_score,
        risk_score: loanApp.risk_score
      },
      kyc_validation: kycData ? {
        document_type: kycData.document_type,
        verified: kycData.is_verified,
        face_match_score: kycData.face_match_score,
        verification_method: 'AgentFinance AI Engine'
      } : null,
      consents: consents || [],
      events: events.map(e => ({
        timestamp: e.created_at,
        event: e.event,
        metadata: e.metadata
      }))
    };

    // 6. Generate SHA-256 Digest
    const serializedReport = JSON.stringify(reportJson);
    const hash = await generateHash(serializedReport);

    // 7. Save Immutable Record to Database
    await supabase.from('audit_reports').insert([{
      application_id: applicationId,
      report_json: reportJson,
      sha256_hash: hash,
      generated_by: generatedBy
    }]);

    // 8. Generate Markdown Format
    const md = `
# Regulatory Audit Report
**Hash:** \`${hash}\`
**Generated At:** ${new Date().toISOString()}
**Generated By:** ${generatedBy}

## 1. Applicant Profile
- **Application ID:** ${loanApp.id}
- **Name:** ${loanApp.profiles?.name || 'N/A'}
- **Phone:** ${loanApp.profiles?.phone || 'N/A'}
- **Status:** ${loanApp.status} (${loanApp.application_stage})

## 2. Risk & KYC Data
- **Fraud Score:** ${loanApp.fraud_risk_score || 'N/A'}
- **Trust Score:** ${loanApp.trust_score || 'N/A'}
- **Risk Score:** ${loanApp.risk_score || 'N/A'}
- **KYC Verified:** ${kycData?.is_verified ? 'Yes' : 'No'}

## 3. Explicit Consents
${consents && consents.length > 0 ? consents.map(c => `- **${new Date(c.timestamp).toLocaleString()}**: ${c.consent_text} (IP: ${c.user_ip})`).join('\n') : 'No consents recorded.'}

## 4. Event Trail
${events.map(e => `- \`[${new Date(e.created_at).toISOString()}]\` - **${e.event}** \n  *Meta:* ${JSON.stringify(e.metadata)}`).join('\n')}

---
*End of Report*
    `.trim();

    return {
      json: reportJson,
      md,
      hash
    };

  } catch (err) {
    console.error('Audit Generation Error', err);
    throw err;
  }
};
